# -*- coding: utf-8 -*-
"""Slackbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18NZ3naxh01PrXUkhu1azL1S9PGiV_hsy
"""

!pip install slack
!pip install slacker

import slack
from slacker import Slacker
#from IPython.display import Image
import requests
import pandas as pd
import json
import matplotlib.pyplot as plt
import numpy as np
import time
from datetime import datetime

token = 'token here'
slack = Slacker(token)

print(datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ'))

# Check for success
if slack.api.test().successful:
    print(
        f"Connected to {slack.team.info().body['team']['name']}.")
else:
    print('Try Again!')

url='https://data.ripple.com/v2/ledgers/'+ datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ')

resmain= requests.get(url)
x=resmain.json()
x['ledger']['tx_count'] + ' LedgerIndex: '+ str(x['ledger']['ledger_index'])

def check_tx_count_great200():
    url='https://data.ripple.com/v2/ledgers/'+ datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ')
    #ledger_identifier=2020-01-22T11:20:00Z\
    resmain= requests.get(url)
    x=resmain.json()
    if (int(x['ledger']['tx_count'])>70):
        return True, x
    else:
        return False, x

i = 0
while i<1000:
  print(i)
  check, x = check_tx_count_great200()
  print(str(x['ledger']['tx_count']))
  print(str(x['ledger']['ledger_index']))
  i=i+1
  time.sleep(2)

i = 0
no_repeat = ''
ledger =''
while i<10000:
  print(i)
  check, x = check_tx_count_great200()
  if check:
    a = str(x['ledger']['tx_count'])
    ledger = str(x['ledger']['ledger_index'])
    if ledger != no_repeat:
        linkk = 'https://livenet.xrpl.org/ledgers/' + ledger
        message = '<!everyone> *Careful bros, unusual amount of transactions per ledger*\n We got ' + a + ' transactions per ledger in the last period\n Check out ledger ' + ledger + '\nHere\n' + linkk
        #public channel
        slack.chat.post_message(channel='#anomaly_detection',
                                  text= message,
                                  username='capstone_bot',
                                  icon_emoji=':female-firefighter:')
  no_repeat = ledger
  i=i+1
  time.sleep(2)